<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ITUs-MacBook-Pro-5.local" name="edu.itu.bridge.tests.functional.candidate.education.F_ManageEducationInfoTest" tests="5" failures="0" timestamp="3 Feb 2015 20:12:44 GMT" time="131.029" errors="1">
  <testcase name="F_AddNewRecordAllFieldsTypeInAndCancelIt" time="16.459" classname="edu.itu.bridge.tests.functional.candidate.education.F_ManageEducationInfoTest">
    <error type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at edu.itu.bridge.tests.base.ActionService.isElementNotPresent(ActionService.java:103)
	at edu.itu.bridge.tests.functional.candidate.education.F_ManageEducationInfoTest.F_AddNewRecordAllFieldsTypeInAndCancelIt(F_ManageEducationInfoTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
]]>
    </error>
  </testcase> <!-- F_AddNewRecordAllFieldsTypeInAndCancelIt -->
  <testcase name="F_AddNewRecordWithRequiredFieldsOnly" time="34.343" classname="edu.itu.bridge.tests.functional.candidate.education.F_ManageEducationInfoTest"/>
  <testcase name="F_EducationInfo" time="17.263" classname="edu.itu.bridge.tests.functional.candidate.education.F_ManageEducationInfoTest"/>
  <testcase name="F_AddNewRecordTypeAllFieldsAndSaveIt" time="44.179" classname="edu.itu.bridge.tests.functional.candidate.education.F_ManageEducationInfoTest"/>
  <testcase name="F_ChekingErrorMesagesWhenRequiredFieldsAreEmpty" time="18.785" classname="edu.itu.bridge.tests.functional.candidate.education.F_ManageEducationInfoTest"/>
</testsuite> <!-- edu.itu.bridge.tests.functional.candidate.education.F_ManageEducationInfoTest -->
